/**
 * Cleartext Theme — Client-side Search
 * Uses search.xml generated by Hexo
 * Includes recent search history via localStorage
 */
(function () {
  'use strict';

  var searchToggle = document.getElementById('search-toggle');
  var searchOverlay = document.getElementById('search-overlay');
  var searchInput = document.getElementById('search-input');
  var searchClose = document.getElementById('search-close');
  var searchResults = document.getElementById('search-results');

  if (!searchToggle || !searchOverlay) return;

  var searchData = [];
  var searchIndex = null;
  var searchLoaded = false;
  var HISTORY_KEY = 'cleartext-search-history';
  var MAX_HISTORY = 8;

  // --- Search History ---
  function getHistory() {
    try { return JSON.parse(localStorage.getItem(HISTORY_KEY)) || []; }
    catch (e) { return []; }
  }
  function saveHistory(query) {
    var h = getHistory().filter(function (q) { return q !== query; });
    h.unshift(query);
    if (h.length > MAX_HISTORY) h.pop();
    localStorage.setItem(HISTORY_KEY, JSON.stringify(h));
  }
  function clearHistory() {
    localStorage.removeItem(HISTORY_KEY);
    renderHistory();
  }
  function renderHistory() {
    var history = getHistory();
    var container = document.getElementById('search-history');
    if (!container) return;
    if (history.length === 0) {
      container.style.display = 'none';
      return;
    }
    container.style.display = 'block';
    var html = '<div class="search-history-title">Recent searches</div><ul class="search-history-list">';
    history.forEach(function (q) {
      html += '<li class="search-history-item"><button type="button">' + escHtml(q) + '</button></li>';
    });
    html += '<li class="search-history-item"><button class="search-history-clear" type="button">Clear all</button></li>';
    html += '</ul>';
    container.innerHTML = html;
    // Click to reuse
    container.querySelectorAll('.search-history-item button:not(.search-history-clear)').forEach(function (btn) {
      btn.addEventListener('click', function () {
        searchInput.value = btn.textContent;
        performSearch(btn.textContent.trim());
      });
    });
    var clearBtn = container.querySelector('.search-history-clear');
    if (clearBtn) clearBtn.addEventListener('click', clearHistory);
  }
  function escHtml(s) { var d = document.createElement('div'); d.textContent = s; return d.innerHTML; }

  // Load search.xml
  function loadSearchData() {
    if (searchLoaded) return;
    searchLoaded = true;
    var url = searchOverlay.getAttribute('data-search-url') || '/search.xml';
    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4 && xhr.status === 200) {
        parseSearchXML(xhr.responseText);
      }
    };
    xhr.send();
  }

  // Parse XML into searchable data
  function parseSearchXML(xmlText) {
    var parser = new DOMParser();
    var xmlDoc = parser.parseFromString(xmlText, 'text/xml');
    var entries = xmlDoc.querySelectorAll('entry');

    searchData = Array.from(entries).map(function (entry) {
      return {
        title: entry.querySelector('title')?.textContent || '',
        url: entry.querySelector('url')?.textContent || '',
        content: entry.querySelector('content')?.textContent || '',
        summary: entry.querySelector('summary')?.textContent || '',
        date: entry.querySelector('date')?.textContent || '',
        updated: entry.querySelector('updated')?.textContent || '',
        categories: entry.querySelector('categories')?.textContent || '',
        tags: entry.querySelector('tags')?.textContent || ''
      };
    });

    // Build simple index (title + content)
    searchIndex = searchData.map(function (item, idx) {
      return {
        id: idx,
        text: (item.title + ' ' + item.content + ' ' + item.categories + ' ' + item.tags).toLowerCase().replace(/<[^>]+>/g, '')
      };
    });
  }

  // Perform search
  function performSearch(query) {
    if (!searchIndex || query.length < 2) {
      searchResults.innerHTML = '<p class="search-hint">Type at least 2 characters</p>';
      return;
    }

    var q = query.toLowerCase();
    saveHistory(query);
    var results = [];

    // Escape regex special chars in query
    var escapedQ = q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    searchIndex.forEach(function (item) {
      if (item.text.includes(q)) {
        var data = searchData[item.id];
        var content = data.content || '';
        var idx = content.toLowerCase().indexOf(q);
        var snippet = '';
        if (idx >= 0) {
          var start = Math.max(0, idx - 50);
          var end = Math.min(content.length, idx + 100);
          snippet = '...' + content.substring(start, end) + '...';
        } else {
          snippet = content.substring(0, 150) + '...';
        }
        results.push({
          title: data.title,
          url: data.url,
          snippet: snippet,
          escapedQ: escapedQ,
          date: data.date,
          updated: data.updated,
          categories: data.categories,
          tags: data.tags
        });
      }
    });

    displayResults(results);
  }

  // Display results
  function displayResults(results) {
    if (results.length === 0) {
      searchResults.innerHTML = '<p class="search-no-results">No matching articles found.</p>';
      return;
    }

    var html = '<div class="search-results-count">Found ' + results.length + ' result' + (results.length > 1 ? 's' : '') + '</div>';
    html += '<ul class="search-results-list">';
    results.forEach(function (r) {
      // Highlight matching text
      var highlight = function (text, q) {
        if (!text || !q) return escHtml(text);
        var regex = new RegExp('(' + q + ')', 'gi');
        return escHtml(text).replace(regex, '<mark>$1</mark>');
      };

      var title = highlight(r.title, r.escapedQ);
      var snippet = highlight(r.snippet, r.escapedQ);
      var categories = r.categories ? r.categories.split(', ').map(function (c) {
        return '<span class="search-result-category">' + escHtml(c) + '</span>';
      }).join('') : '';
      var tags = r.tags ? r.tags.split(', ').map(function (t) {
        return '<span class="search-result-tag">#' + escHtml(t) + '</span>';
      }).join('') : '';

      html += '<li>' +
        '<a href="' + r.url + '" class="search-result-link">' +
        '<h4 class="search-result-title">' + title + '</h4>' +
        '<div class="search-result-meta">' +
        (r.date ? '<span class="search-result-date">' + r.date + '</span>' : '') +
        (r.updated ? '<span class="search-result-updated">Updated ' + r.updated + '</span>' : '') +
        (categories ? '<span class="search-result-categories">' + categories + '</span>' : '') +
        (tags ? '<span class="search-result-tags">' + tags + '</span>' : '') +
        '</div>' +
        '<p class="search-result-snippet">' + snippet + '</p>' +
        '</a>' +
        '</li>';
    });
    html += '</ul>';
    searchResults.innerHTML = html;
  }

  // Open/close overlay
  function openSearch() {
    searchOverlay.classList.add('active');
    searchInput.focus();
    searchInput.value = '';
    searchResults.innerHTML = '';
    renderHistory();
    document.body.style.overflow = 'hidden';
  }

  function closeSearch() {
    searchOverlay.classList.remove('active');
    searchInput.value = '';
    searchResults.innerHTML = '';
    document.body.style.overflow = '';
  }

  // Event listeners
  searchToggle.addEventListener('click', openSearch);
  searchClose.addEventListener('click', closeSearch);
  searchOverlay.addEventListener('click', function (e) {
    if (e.target === searchOverlay) closeSearch();
  });

  // Close with Escape
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && searchOverlay.classList.contains('active')) {
      closeSearch();
    }
  });

  // Search as you type
  var debounceTimer;
  searchInput.addEventListener('input', function () {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(function () {
      performSearch(searchInput.value.trim());
    }, 200);
  });

  // Load data on first open
  searchToggle.addEventListener('click', function () {
    if (!searchIndex) {
      loadSearchData();
    }
  });

  // Preload on page load
  setTimeout(loadSearchData, 1000);
})();